bjshare: Also parse the international titles from the 24h search
Jackett/Jackett pull request #10501
Opened 2020-12-13 22:46 UTC by christianfds

Now both kinds of search's uses the "ParseTitle" method.

Signed-off-by: Christian Franchin dos Santos <christian@corp.kionux.com.br>

2020-12-14 09:52 UTC, ngosang requested changes

2020-12-14 09:52 UTC, ngosang commented on src/Jackett.Common/Indexers/BJShare.cs
> +            string[] results = match.Groups[1].Value.Split('/');
This line can throw an exception, change it for:
```
return match.Success ? match.Groups[1].Value.Split('/')[0] : title;
```

2020-12-19 18:21 UTC, ngosang commented
@christianfds are you going to finish this PR?

2020-12-19 18:40 UTC, christianfds commented
> @christianfds are you going to finish this PR?

I've been busy and forgot about it, i made the change as requested.

2020-12-19 19:06 UTC, merged

2020-12-19 19:07 UTC, ngosang commented
thank you!