[Draft] Fix AniDub search
Jackett/Jackett pull request #10972
Opened 2021-01-30 21:06 UTC by dm3ch

Try to make search not return unrelated results and not broke search without punctuation things and e.t.c

#8962
#10931

2021-01-31 06:20 UTC, ilike2burnthing requested changes

2021-01-31 06:20 UTC, ilike2burnthing commented on src/Jackett.Common/Indexers/AniDUB.cs
> +
```suggestion

```
remove whitespace

2021-01-31 10:48 UTC, ngosang approved these changes

2021-01-31 10:48 UTC, ngosang commented
@ilike2burnthing if this is working you can merge

2021-01-31 12:24 UTC, merged

2021-02-01 05:36 UTC, ilike2burnthing commented
[v0.17.437](https://github.com/Jackett/Jackett/releases/tag/v0.17.437)