Update categories
Jackett/Jackett pull request #10994
Opened 2021-02-01 15:43 UTC by RicardoVelaC

Adds new Movies/HD category for music HD concerts

That fix latest errors in log when search in Torrentland

2021-02-01 16:56 UTC, ilike2burnthing requested changes

2021-02-01 16:56 UTC, ilike2burnthing commented on src/Jackett.Common/Definitions/torrentland.yml
> +    - {id: 88, cat: Movies/HD, desc: "Videos Musicales"}
```suggestion
    - {id: 88, cat: Movies/HD, desc: "Peliculas - Videos Musicales"}
```

2021-02-01 16:57 UTC, ilike2burnthing commented
Would a more accurate category be `Audio/Video` rather than `Movies/HD`?

Categories can be found here - https://github.com/Jackett/Jackett/wiki/Jackett-Categories

2021-02-01 18:09 UTC, RicardoVelaC commented on src/Jackett.Common/Definitions/torrentland.yml
> +    - {id: 88, cat: Movies/HD, desc: "Videos Musicales"}
```suggestion
    - {id: 88, cat: Audio/Video, desc: "Peliculas - Videos Musicales"}
```

Yes, it's better

2021-02-01 19:46 UTC, merged

2021-02-02 07:57 UTC, ilike2burnthing commented
Thanks - [v0.17.449](https://github.com/Jackett/Jackett/releases/tag/v0.17.449)