desitorrents: migrate to c#. resolves #11904
Jackett/Jackett pull request #11909
Opened 2021-06-13 00:39 UTC by ilike2burnthing

2021-06-13 00:40 UTC, ilike2burnthing commented
bad bot...

2021-06-13 02:02 UTC, ilike2burnthing commented
Logs in fine, search returns feed, but it errors out with:
```
Error on 20210613021003 for DesiTorrents.txtSystem.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Jackett.Common.Indexers.Abstract.GazelleTracker.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\Abstract\GazelleTracker.cs:line 232
```
```
Jackett.Common.IndexerException: Exception (desitorrents): Invalid URI: The format of the URI could not be determined.
 ---> System.Exception: Parse error
 ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Jackett.Common.Indexers.Abstract.GazelleTracker.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\Abstract\GazelleTracker.cs:line 232
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 761
   at Jackett.Common.Indexers.Abstract.GazelleTracker.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\Abstract\GazelleTracker.cs:line 265
   at Jackett.Common.Indexers.DesiTorrents.PerformQuery(TorznabQuery query) in D:\a\1\s\src\Jackett.Common\Indexers\DesiTorrents.cs:line 62
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 385
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 393
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query, Boolean isMetaIndexer) in D:\a\1\s\src\Jackett.Common\Indexers\BaseIndexer.cs:line 735
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in D:\a\1\s\src\Jackett.Common\Services\IndexerManagerService.cs:line 307
   at Jackett.Server.Controllers.IndexerApiController.Test() in D:\a\1\s\src\Jackett.Server\Controllers\IndexerApiController.cs:line 132
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in D:\a\1\s\src\Jackett.Server\Middleware\CustomExceptionHandler.cs:line 61
```
Which points to:
https://github.com/Jackett/Jackett/blob/7a28412d22cbb5fd58ec204dc36d30fdc552445c/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs#L230-L232
External posters are formatted as `"cover":"https:\/\/img.onaroll.net\/images\/75abe608de9ee2bfa5f7c1e5260a5b0e.md.jpg"` whereas local posters are `"cover":"2021\/original_152222_manual_3.jpg"` (actual URL is `https://desitorrents.tv/static//media/posters/2021/original_152222_manual_3.jpg`). I think it's tripping over the latter, though I have no idea how to resolve that.

2021-06-13 02:04 UTC, ilike2burnthing commented
@seeyabye does the above make sense as cause of this issue?

If so, @LokiThor2021 is this resolvable on your side?

2021-06-13 02:55 UTC, ilike2burnthing commented
Just realising `ajax.php` is missing `category` as well.

`CategoryID` is returned in `torrents.php?action=json` but much of it isn't compatible with Gazelle, so would require an actual C# dev to make a separate indexer for it.

2021-06-13 04:57 UTC, seeyabye commented
> @seeyabye does the above make sense as a cause of this issue?
> 
> If so, @LokiThor2021 is this resolvable on your side?

The error is definitely caused by a badly formatted poster URL string that was then passed into `Uri()`. It would require additional checks in `GazelleTracker`'s abstract for badly formatted poster Url.

> Just realising `ajax.php` is missing `category` as well.
> 
> `CategoryID` is returned in `torrents.php?action=json` but much of it isn't compatible with Gazelle, so would require an actual C# dev to make a separate indexer for it.

I don't have an account for this tracker, so I can't help much, but if someone has an invite, I could try writing the indexer.

2021-06-13 16:55 UTC, LokiThor2021 commented
Posters are messed up and is something i plan to fix soon regarding the category in ajax.php what's the endpoint for that ?

2021-06-13 17:08 UTC, LokiThor2021 commented
@seeyabye  can you share your email i can invite you :)

2021-06-13 17:20 UTC, ilike2burnthing commented
Category is just `category` (like grabs is `snatches` and freelech is `isFreeleech`) and is the category ID number:
https://github.com/Jackett/Jackett/blob/313a2fd7845fec1cb853094436a4592841a3b60d/src/Jackett.Common/Indexers/Abstract/GazelleTracker.cs#L345-L357

2021-06-13 18:05 UTC, LokiThor2021 commented
added category to  ajax.php?action=browse

2021-06-13 20:03 UTC, ilike2burnthing commented
Thanks, it needs to be the category ID number though, so `1` for movies, `2` for tv shows, etc.

Not sure if it's case sensitive, but it's a lower case `c` in `category`.

2021-06-13 21:27 UTC, seeyabye commented
@LokiThor2021 please send it to seeyabye91 [at] gmail.com. Thanks.

2021-06-14 07:04 UTC, LokiThor2021 commented
@ilike2burnthing fixed

2021-06-14 12:17 UTC, geek-baba commented
Looks like issue is resolved but not able to merge this with master?

2021-06-14 13:55 UTC, seeyabye commented
@ilike2burnthing 

I took a look at this, and it's a little bit more complicated given that it's not quite compatible with `GazelleTracker.cs` right out of the box. Several issues that requires fixing:

- Posters are occasionally returning relative links. A simple fix on `GazelleTracker.cs` @ line 231 is to include an additional check
```c#
if (!string.IsNullOrEmpty(cover) && cover.StartsWith("http"))
```
- The categories are not showing if a filter is applied. A temporary fix would be to assume that categories are filtered correctly. See [Oppaitime.cs](https://github.com/Jackett/Jackett/blob/master/src/Jackett.Common/Indexers/OppaiTime.csl).

The last issue will require some refactoring work to be done in `GazelleTracker.cs`. When I can find the time, I will work on that, but for now, `GazelleTracker.cs` isn't quite abstract enough to fit all scenarios.

2021-06-14 15:29 UTC, ilike2burnthing commented
@seeyabye 
> if (!string.IsNullOrEmpty(cover) && cover.StartsWith("http"))

This worked, thanks.

> The categories are not showing if a filter is applied. A temporary fix would be to assume that categories are filtered correctly.

Do you mean when searching by category, categories aren't shown? I had no issue with that, `https://desitorrents.tv/ajax.php?action=browse&order_by=time&order_way=desc`
and `https://desitorrents.tv/ajax.php?action=browse&order_by=time&order_way=desc&filter_cat[1]=1`
both show `category`.

Rather the issue I'm running into at the moment is that in Jackett all categories are being displayed as Movies, despite them being correctly labelled in the json output.

2021-06-14 22:18 UTC, seeyabye commented
> Do you mean when searching by category, categories aren't shown? I had no issue with that, `https://desitorrents.tv/ajax.php?action=browse&order_by=time&order_way=desc`
> and `https://desitorrents.tv/ajax.php?action=browse&order_by=time&order_way=desc&filter_cat[1]=1`
> both show `category`.
> 
> Rather the issue I'm running into at the moment is that in Jackett all categories are being displayed as Movies, despite them being correctly labelled in the json output.

It's probably a related issue. `GazelleTracker` currently defaults all categories that it can't map to `10001` custom category. You will see categories for movies only like `10001`. Filtering by category with 'Tv Shows' which result in `10002` and above will return no results.

2021-06-14 22:25 UTC, ilike2burnthing commented
Yea, saw that as well, I assumed it was because they were all being classed as Movies. Given that `category` is present and showing the correct categories, why isn't Jackett using it?

2021-06-14 22:37 UTC, seeyabye commented
The category returned by desitorrents is under `group` while `GazelleTracker.cs` expects it to be under `torrent`

<details><summary>sample json result</summary>

```json
{
  "status": "success",
  "response": {
    "currentPage": 1,
    "pages": 77,
    "results": [
      {
        "groupId": 152853,
        "groupName": "Khwabon Ke Parindey",
        "cover": "https://www.socialketchup.in/wp-content/uploads/2021/06/IMG-20210604-WA0003.jpg",
        "tags": [
          "drama",
          "comedy",
          "jatt"
        ],
        "bookmarked": false,
        "groupYear": 0,
        "groupTime": 1623661783,
        "maxSize": 2125630200,
        "totalSnatched": 1,
        "totalSeeders": 2,
        "totalLeechers": 0,
        "category": 2,
        "torrents": [
          {
            "torrentId": 199397,
            "media": "Web",
            "container": "MKV",
            "codec": "x265",
            "resolution": "1080p",
            "audio": "AC3 2.0",
            "lang": "Hindi",
            "subbing": "",
            "archive": null,
            "fileCount": 6,
            "time": "2021-06-14 11:09:43",
            "size": 2125630200,
            "snatches": 1,
            "seeders": 2,
            "leechers": 0,
            "isFreeleech": true,
            "isNeutralLeech": false,
            "isPersonalFreeleech": false,
            "canUseToken": false,
            "hasSnatched": false
          }
        ]
      },
```

</details>

Perhaps @LokiThor2021 could consider changing this part, otherwise, it will have to wait until I figure out how I could refactor out `GazelleTracker.cs`.

2021-06-14 22:47 UTC, LokiThor2021 commented
@seeyabye will fix it soon

2021-06-14 22:57 UTC, seeyabye commented
@LokiThor2021 my apologies, but perhaps there's no need to change on your end. Technically the returned results by desitorrents are correct.

@ilike2burnthing I've proposed a small change and it should fix the issue.

2021-06-14 22:58 UTC, seeyabye requested changes

2021-06-14 22:58 UTC, seeyabye commented on src/Jackett.Common/Indexers/DesiTorrents.cs
> +        }
Add the following additional function and it should fix the issue on categories:

```c#
        protected override bool ReleaseInfoPostParse(ReleaseInfo release, JObject torrent, JObject result)
        {
            // Add missing category information
            var category = (string)result["category"];
            release.Category = MapTrackerCatToNewznab(category);
            return true;
        }
```

2021-06-15 02:29 UTC, ilike2burnthing commented
Yep, that's working fine. Thanks to both of you for your help.

2021-06-15 02:29 UTC, merged