Fix bj-share adult categories
Jackett/Jackett pull request #12806
Opened 2022-01-11 17:44 UTC by dctorrent1337

2022-01-11 17:49 UTC, garfield69 requested changes
Categories 19 and 20 are already in use earlier in the category table.
Can you please examine all the category ids and cross check. 
There cannot be duplicate ids for different category types.
Thanks.

2022-01-11 21:34 UTC, dctorrent1337 commented
It there any reason I cannot use TorznabCatType.BooksEbook and TorznabCatType.BooksMagazines? I have seen them in other trackers definitions. 

```
...
/home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs(106,50): error CS0117: 'TorznabCatType' does not contain a definition for 'BooksMagazines' [/home/vsts/work/1/s/src/Jackett.Common/Jackett.Common.csproj]
/home/vsts/work/1/s/src/Jackett.Common/Indexers/BJShare.cs(107,51): error CS0117: 'TorznabCatType' does not contain a definition for 'BooksEbook' [/home/vsts/work/1/s/src/Jackett.Common/Jackett.Common.csproj]
...
```

2022-01-11 22:55 UTC, garfield69 commented
Have a look at https://github.com/Jackett/Jackett/wiki/Jackett-Categories for the valid category names, and in particular, the last section about C# names ;-)

2022-01-11 23:39 UTC, garfield69 requested changes

2022-01-11 23:39 UTC, garfield69 commented on src/Jackett.Common/Indexers/BJShare.cs
> +            AddCategoryMapping(10, TorznabCatType.Books, "E-Books");
```suggestion
            AddCategoryMapping(10, TorznabCatType.BooksEBook, "E-Books");
```

2022-01-12 01:12 UTC, garfield69 approved these changes

2022-01-12 01:13 UTC, merged

2022-01-12 01:13 UTC, garfield69 commented
Thank you.

2022-01-12 01:13 UTC, DaniloNC commented
Thank YOU!

2022-01-12 05:00 UTC, garfield69 commented
v0.20.294