Fix torrent9 selectors:
Jackett/Jackett pull request #13162
Opened 2022-04-16 21:40 UTC by Edouard-chin

Hello 👋 , thank you for this project, it's really cool!

- Torrent9 slightly modified their markups and added a new table
  cell which shifts the rest.

  This is the new markup for a result

  ```html
  <tr>
    <td>
      <i class="fa fa-tv" style="color:#404040"></i>
      <a title="Lupin Saison 1 FRENCH HDTV" href="/torrent/76158/lupin-saison-1-french-hdtv" style="color:#000; font-size:12px; font-weight:bold;"><h3><span class="blue">Lupin</span> Saison 1 FRENCH HDTV</h3></a>
    </td>
    <td style="font-size:12px">14/01/2021</td>
    <td style="font-size:12px">1.6Go</td>
    <td style="font-size:13px;text-align:right; padding-right:5px">
      <span class="seed_ok">2264 <img class="hidden-md" src="/Public/images/up.png"></span>
    </td>
    <td style="font-size:13px;text-align:right; padding-right:5px">573 <img class="hidden-md" src="/Public/images/down.png"></td>
  </tr>
  ```

<img width="1059" alt="Screenshot 2022-04-16 at 23 35 52" src="https://user-images.githubusercontent.com/8122246/163692059-ab0720c9-302a-4e58-a006-6d14c4ae1ae2.png">

2022-04-16 23:13 UTC, ilike2burnthing requested changes
GitHub won't let me tag the search path line, but it also needs changed.
You can use `{{ .Today.Year }}` to search by the current year.

2022-04-16 23:13 UTC, ilike2burnthing commented on src/Jackett.Common/Definitions/torrent9.yml
>        text: now
Date can now be added

2022-04-19 21:03 UTC, garfield69 approved these changes
amended.
Thank you.

2022-04-19 21:04 UTC, merged

2022-04-19 21:31 UTC, Edouard-chin commented
Thanks for amending and sorry for not doing it myself, got distracted on other stuff.

2022-04-20 06:06 UTC, garfield69 commented
v0.20.929