[Indexers Feature] Add colon as a supported character inside TorznabQueries and bring back special characters in Mejortorrent
Jackett/Jackett pull request #13761
Opened 2022-12-07 23:55 UTC by lucasenicora

Follow up on this [Pull Request](https://github.com/Jackett/Jackett/pull/13756)

On top of adding the colon as a valid value for the TorznabQueries, I've refactored the solution for #13716. Instead of only keeping the alpha numerical values, I've stripped the offending unicode characters, and left everything else. This allows characters such as `:` `à` or `ñ` to be used in queries

2022-12-08 00:31 UTC, ilike2burnthing requested changes
Unfortunately, this doesn't appear to be working as intended.

Searching for `Vengadores: Endgame` results in `q=Vengadores+Endgame`, same as it does currently.

Similarly, searching for `Japón` results in `q=Jap+n`.

2022-12-08 00:31 UTC, ilike2burnthing commented on src/Jackett.Common/Indexers/MejorTorrent.cs
> +            // so we need to strip them
```suggestion
            // Server returns a 500 error if a UTF character higher than \u00FF (ÿ) is included,
            // so we need to strip them
            // searchTerm = Doctor Who 2005
```

Restore removed example.

2022-12-08 22:16 UTC, lucasenicora commented
I'm sorry for that @ilike2burnthing. I really forgot to commit the most important line. I shouldn't be coding so late.

I've now pushed it, and it fixes the issue when running manual queries from withing Jackett UI. Unfortunately, this doesn't seem to fix the error from Radarr itself, since Radarr also strips the colon when executing the request against Jackett (according to my rudimentary tests adding logs here and there).
If I have some more time I'll try to sneak into Radarr repo to see if I can find where those characters are being stripped out. 

But for the moment, I would say that from Jackett perspective, that's all I can do

2022-12-08 23:38 UTC, ilike2burnthing commented
Try enabling `SupportsRawSearch` - https://github.com/Jackett/Jackett/pull/13409

2022-12-09 00:02 UTC, lucasenicora commented
That did the trick! 👏 👏

2022-12-09 00:16 UTC, merged

2022-12-09 00:17 UTC, ilike2burnthing commented
Thanks! Next release will be in ~6hrs.