assorted: use GetArgumentFromQueryString and other minor fixes
Jackett/Jackett pull request #13941
Opened 2023-01-29 03:39 UTC by mynameisbogdan

- use `ParseUtil.GetArgumentFromQueryString()` instead of `Split` (there a few more, but I can't test or find out what's the name of param)
- use [NameValueCollection.Set()](https://learn.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection.set?view=net-6.0#remarks)
- use `WebUtility.HtmlDecode()` for titles taken from download links
- ignore the hardcoded timezone in HDTS
- ST: use the date added before falling back to elapsed time, and change encoding to UTF-8 to match both header and meta `content-type` charset.

2023-01-29 05:59 UTC, ilike2burnthing requested changes
HDSpace and ImmortalSeed appear to be fine, just the one issue with SceneTime.

@garfield69 can you test XSpeeds?

The changes to HDTorrents seem fairly simple, don't think there's any need to ask ngosang to test it.

2023-01-29 05:59 UTC, ilike2burnthing commented on src/Jackett.Common/Indexers/SceneTime.cs
> -                    release.Category = MapTrackerCatToNewznab(catId);
This was added in https://github.com/Jackett/Jackett/commit/bef73a5f50dfef9739571bb1b1a2f07675d0caa5 to handle missing categories. It appears to be still be an issue. If you search `blue` you get the following error:

```text
2023-01-29 05:40:17 | Error | Error on 20230129054017 for SceneTime.txtSystem.NullReferenceException: Object reference not set to an instance of an object.    at Jackett.Common.Indexers.SceneTime.ParseResponse(TorznabQuery query, String htmlResponse) in D:\a\1\s\src\Jackett.Common\Indexers\SceneTime.cs:line 183
2023-01-29 05:40:17 | Error | Jackett.Common.IndexerException: Exception (scenetime): Object reference not set to an instance of an object.
```

2023-01-29 06:34 UTC, ilike2burnthing approved these changes

2023-01-29 07:17 UTC, merged

2023-01-29 07:21 UTC, garfield69 commented
>use ParseUtil.GetArgumentFromQueryString() instead of Split (there a few more, but I can't test or find out what's the name of param)

if you can identify which other indexers you are referring to, I may be able to provide temp access while you code/test (if I have an account)

2023-01-30 06:01 UTC, garfield69 commented
v0.20.2767