monikadesign: new site init
Jackett/Jackett pull request #14280
Opened 2023-04-28 15:38 UTC by xiaoxi654

2023-04-28 18:25 UTC, garfield69 commented on src/Jackett.Common/Definitions/monikadesign-api.yml
> +# json UNIT3D 6.0.4
What are the seeding time requirements for downloaded torrents, and/or is there a minimum share ratio?
for example, MST 48 hours, MR 1.0

2023-04-28 19:04 UTC, garfield69 reviewed
If the site is really a unit3d 6.4.1 as suggested by the login page eye catcher, then 
we should be able to use `category: selector: category_id` instead of `categorydesc: selector: category`
and `poster: selector: meta.poster` instead of `poster: selector: poster`

unless the site has a 6.4.1 app.js and is still using a 6.0.4 unit3d.js, which is an odd combo but not out of the realms of possibility.

Could you please provide a HTML dump of https://monikadesign.uk/torrents?perPage=25 so we can do some cross checking?
See https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-html-source 
Thanks.

2023-04-28 23:57 UTC, xiaoxi654 commented on src/Jackett.Common/Definitions/monikadesign-api.yml
> +# json UNIT3D 6.0.4
> What are the seeding time requirements for downloaded torrents, and/or is there a minimum share ratio?
> for example, MST 48 hours, MR 1.0

There’s no limit about seeding time or single seed share ratio requirement.

2023-04-29 00:09 UTC, xiaoxi654 commented
> If the site is really a unit3d 6.4.1 as suggested by the login page eye catcher, then we should be able to use `category: selector: category_id` instead of `categorydesc: selector: category` and `poster: selector: meta.poster` instead of `poster: selector: poster`
> 
> unless the site has a 6.4.1 app.js and is still using a 6.0.4 unit3d.js, which is an odd combo but not out of the realms of possibility.
> 
> Could you please provide a HTML dump of https://monikadesign.uk/torrents?perPage=25 so we can do some cross checking? See https://github.com/Jackett/Jackett/wiki/Troubleshooting/#how-to-provide-html-source Thanks.

It’s more like I forget to change the version in comment, I have only copy-pasted an another unit3d api definition. I’ll check those suggestions when I have time, thanks!

2023-04-29 08:35 UTC, garfield69 requested changes

2023-04-29 08:35 UTC, garfield69 commented on src/Jackett.Common/Definitions/monikadesign-api.yml
> +      selector: category
```suggestion
      selector: category_id
```

2023-04-29 08:35 UTC, garfield69 commented on src/Jackett.Common/Definitions/monikadesign-api.yml
> +      selector: poster
```suggestion
      selector: meta.poster
```

2023-04-29 08:37 UTC, garfield69 requested changes

2023-04-29 08:37 UTC, garfield69 commented on src/Jackett.Common/Definitions/monikadesign-api.yml
> +    categorydesc:
```suggestion
    category:
```

2023-05-03 08:13 UTC, garfield69 approved these changes

2023-05-03 08:16 UTC, merged