cardigann: ignore disabled or unchecked inputs in login
Jackett/Jackett pull request #14338
Opened 2023-05-18 12:02 UTC by mynameisbogdan

with fixing learnbits with empty values I discovered that cardigann uses unchecked and even disabled inputs, which aren't used in the sent form body in any real browser.

and it's a BC break in Prowlarr...

2023-05-18 18:59 UTC, garfield69 requested changes

2023-05-18 18:59 UTC, garfield69 commented on src/Jackett.Common/Definitions/carpt.yml
>      username: "{{ .Config.username }}"
the secret keyword is hidden and is in the payload sent by the browser so this should not be removed from the indexer
```
secret=&username=redacted&password=redacted&two_step_code=&imagestring=redacted&imagehash=redacted
```

2023-05-19 21:55 UTC, ilike2burnthing approved these changes
Resolved issue for only 2 indexers I had a problem with in this build (tested in Jackett and Prowlarr) - https://github.com/Jackett/Jackett/commit/25cdf412c19650f6eaac2bc6acaa3c7549f472a3.

2023-05-19 22:57 UTC, ilike2burnthing commented
Partial improvement - https://github.com/Jackett/Jackett/commit/f018aa252cfa6ec8ecaa0687a959484f8adb704d

`logintype` needed for Prowlarr, specifically `yes` needed for Jackett if it's added. `logout` needed for Prowlarr just for LearnBits 🤷

2023-05-19 23:42 UTC, ilike2burnthing commented
And done ;) working with both now

2023-05-19 23:50 UTC, merged