[New Tracker] exitorrent.org
Jackett/Jackett pull request #14708
Opened 2023-09-23 06:01 UTC by relains

2023-09-23 06:25 UTC, garfield69 requested changes
is this site related to exitorrent.eu?

2023-09-23 06:25 UTC, garfield69 commented on src/Jackett.Common/Definitions/exitorrent-org.yml
> +  - http://exitorrent.org/
The site supports secure connections so lets use it
```suggestion
  - https://exitorrent.org/
```

2023-09-23 06:25 UTC, garfield69 commented on src/Jackett.Common/Definitions/exitorrent-org.yml
> +description: "exitorrent.org is a POLISH Private Torrent Tracker"
```suggestion
description: "exitorrent.org is a POLISH Private Torrent Tracker for MOVIES / TV / GENERAL"
```

2023-09-23 06:25 UTC, garfield69 commented on src/Jackett.Common/Definitions/exitorrent-org.yml
> +    - {id: 43, cat: Books, desc: "AudioBooki"}
```suggestion
    - {id: 43, cat: Audio/Audiobook, desc: "AudioBooki"}
```

2023-09-23 06:25 UTC, garfield69 commented on src/Jackett.Common/Definitions/exitorrent-org.yml
> +    - {id: 31, cat: Books, desc: "Ebooki"}
```suggestion
    - {id: 31, cat: Books/EBook, desc: "Ebooki"}
```

2023-09-23 06:25 UTC, garfield69 commented on src/Jackett.Common/Definitions/exitorrent-org.yml
> +# engine n/a
```suggestion
#TBSource v1.5.0
```

2023-09-23 06:32 UTC, garfield69 requested changes

2023-09-23 06:32 UTC, garfield69 commented on README.md
> + * Exitorrent
```suggestion
 * Exitorrent.org
```
if the site is not related to exitorrent.eu then lets tell them apart
if it is related then leave as is.

2023-09-23 07:01 UTC, garfield69 approved these changes
Fantastic. Thank you for contributing.

2023-09-23 07:10 UTC, merged

2023-09-23 07:11 UTC, garfield69 commented
We've missed the release windows for today, so this will go out with the next release due in about 23 hours from now.

2023-09-24 06:00 UTC, garfield69 commented
v0.21.887

2023-10-08 19:10 UTC, PrzemekSkw commented
Hello, I try that in Jackett and test failed:
```
[exitorrent-org] (testing) Test search in exitorrent.org => Found no results while trying to browse this tracker. This may be an issue with the indexer, or other indexer settings such as search freeleech only etc.
```
I try also in Prowlarr. Test was OK. It sync to Sonarr and Radarr and also test OK in that apps but it don't shows results. 
It shows me results only when I search in nzb360 app in Prowlarr Search engine but don't add to download client.
Open new issue for that?
Regards.

2023-10-08 19:16 UTC, garfield69 commented
@PrzemekSkw  yes, please open a new issue, and since none of the team have an account on that site, we are going to need your help to work out what is going on. 
Please turn on **enhanced** logging, repeat the test and provide the full **enhanced** log file with the new open issue, which includes the _Debug_ and _HTML_. Hopefully this will provide a clue to the problem.
See https://github.com/Jackett/Jackett/wiki/Troubleshooting#how-to-provide-a-jackett-enhanced-log-for-a-ticket for details.