ui: show external access warning
Jackett/Jackett pull request #15017
Opened 2024-01-26 06:27 UTC by mynameisbogdan

2024-01-26 06:35 UTC, garfield69 commented on src/Jackett.Common/Content/index.html
> +        </div>
perhaps add why this is not a good idea, i.e. this is a security risk.

2024-01-26 06:43 UTC, garfield69 requested changes

2024-01-26 06:43 UTC, garfield69 commented on src/Jackett.Common/Content/index.html
> +            <strong><span class="glyphicon glyphicon-alert"></span> Your instance has external access enabled without using an admin password <span class="glyphicon glyphicon-alert"></span></strong>
```suggestion
            <strong><span class="glyphicon glyphicon-alert"></span>Security Risk: Your instance has external access enabled without using an admin password.<span class="glyphicon glyphicon-alert"></span></strong>
```

2024-01-26 06:54 UTC, garfield69 approved these changes

2024-01-26 06:55 UTC, merged

2024-01-26 06:55 UTC, garfield69 commented
Tested. lGtM

2024-02-01 03:50 UTC, virusperfect commented
Can this be disabled? It's super annoying if I already have an authorization layer on top of Jackett.

2024-02-01 19:39 UTC, ilike2burnthing commented
Add the admin password, sign in once, you won't be asked again unless you delete cookies or use a different browser/device.