Add new indexer Wolfmax4K
Jackett/Jackett pull request #15045
Opened 2024-02-09 17:00 UTC by highfredo

#### Description
Add new indexer Wolfmax4K

#### Issues Fixed or Closed by this PR

* Fixes #14511

2024-02-09 17:38 UTC, garfield69 requested changes
Hey, thanks for you contribution!
While I am not a C# dev, I have made some suggestions based on the usual Jackett indexer ethos. I'll get a proper C# to review the code later.

2024-02-09 17:38 UTC, garfield69 commented on src/Jackett.Common/Indexers/Wolfmax4K.cs
> +        public override string[] AlternativeSiteLinks => new[]
if there is only one domain then you don not need to include an alternative site links block ;-)

2024-02-09 17:38 UTC, garfield69 commented on src/Jackett.Common/Indexers/Wolfmax4K.cs
> +
some torznab apps do not like getting results with 0 byte sizes. If the site does not provide a size then we usually guess some default size values 
https://github.com/Jackett/Jackett/blob/7c49cea4b64cc95166250d441d94f1692eb00dcf/src/Jackett.Common/Indexers/DonTorrent.cs#L505-L516
https://github.com/Jackett/Jackett/blob/7c49cea4b64cc95166250d441d94f1692eb00dcf/src/Jackett.Common/Indexers/DonTorrent.cs#L527-L541

2024-02-09 17:47 UTC, garfield69 commented
so the site does not support searching for season and episodes `saving hope s02e01` or even `saving hope temporada 2  capitulo 10` ?
this may cause issues with Sonarr. We may need to strip the season and episode from the query and filter results.

2024-02-09 18:00 UTC, highfredo commented
> so the site does not support searching for season and episodes `saving hope s02e01` or even `saving hope temporada 2 capitulo 10` ? this may cause issues with Sonarr. We may need to strip the season and episode from the query and filter results.

Thanks for your feedback!
As soon as I can I will make the changes

Unfortunately the site does not support searches by episodes, and the filter by categories does not work correctly. 
But the indexer try to fix it [here](https://github.com/highfredo/Jackett/blob/c53332c1dc2208884e104ebf7edb1597ee267931/src/Jackett.Common/Indexers/Wolfmax4K.cs#L260-L281)

So, Sonarr search works :)
![image](https://github.com/Jackett/Jackett/assets/5951524/af16b755-fd44-4351-95a2-d86c75fc4452)

2024-02-09 18:26 UTC, highfredo commented
> Search for S01E02

S01E02 works, but S01E03 fails 🤦

2024-02-09 18:38 UTC, highfredo commented on src/Jackett.Common/Indexers/Wolfmax4K.cs
> +        }
Are you referring to a new class within Wolfmax4K.cs or in its own Wolfmax4KCatType.cs file?

If it is in your own file, where should I place it? I don't see anything similar. In fact, the indexers that I have looked at (dontorrent and mejortorrent) have it like me.

2024-02-10 19:25 UTC, garfield69 approved these changes
Tested, LGTM

2024-02-10 20:03 UTC, merged