assorted unit3d 8.0: use filename for single files
Jackett/Jackett pull request #15155
Opened 2024-03-16 09:48 UTC by mynameisbogdan

#### Description
I noticed UNIT3D 8.0 contains the list of files now and considering their renaming of release titles, I grabbed the same logic I implemented to ANT to use filename for single files. 

Should we add it as an option or always on?

2024-03-16 10:08 UTC, ilike2burnthing requested changes
Looks good. I'd change `_filename` to `title_filename` though.

Would we want to trim the file extension from the end of the title?

2024-03-16 10:16 UTC, ilike2burnthing commented
> I was wondering if maybe some would like to use the titles as they have them on their sites.

Ah, true. Ok so a setting of something like:

`Use filename as title for single file releases`

and set default to true?

> Actually having the extension is a good thing for Radarr/Sonarr, since there are restrictions for `.iso` and some other file extensions.

Good point.

2024-03-16 10:20 UTC, ilike2burnthing approved these changes

2024-03-16 10:21 UTC, merged

2024-03-28 03:08 UTC, garfield69 commented
Re: the extension at the end of titles, does this in any way impact processing of the group names for those that use that feature?
example: was `-GRiMM` now `-GRiMM.mkv`

2024-03-28 03:16 UTC, ilike2burnthing commented
The `Test Parsing` function in Sonarr shows it working fine with the file extension.