Aniliibria fix
Jackett/Jackett pull request #15174
Opened 2024-03-21 15:09 UTC by kekal

Anilibria indexer changes:
* Added season number parsing.
* Fixed several issues with Specials and Movies naming

2024-03-21 23:10 UTC, ilike2burnthing requested changes
Looks good, thanks. A few very minor tweaks and I'll merge this.

2024-03-21 23:10 UTC, ilike2burnthing commented on src/Jackett.Common/Definitions/anilibria.yml
> +      text: "{{ if .Config.stripcyrillic }}{{ else }}{{ .Result.title_ru }} / {{ end }}{{ .Result.title_en_parsed }} {{ .Result._season_number}}E{{ .Result._episodes }} [{{ .Result._quality_type }}.{
```suggestion
      text: "{{ if .Config.stripcyrillic }}{{ else }}{{ .Result.title_ru }} / {{ end }}{{ .Result.title_en_parsed }} {{ .Result._season_number}}E{{ .Result._episodes }} [{{ .Result._quality_type }} {{ .Result._quality_resolution }} {{ .Result._quality_encoder }}]"
```

2024-03-22 09:21 UTC, kekal commented on src/Jackett.Common/Definitions/anilibria.yml
> +    title_old:
Ok

2024-03-22 09:21 UTC, kekal commented on src/Jackett.Common/Definitions/anilibria.yml
> +      text: "{{ if .Config.compatibilitymod }}{{ .Result.title_parsed }}{{ else }}{{ .Result.title_old }}{{ end }}"
ok

2024-03-22 09:22 UTC, kekal commented on src/Jackett.Common/Definitions/anilibria.yml
> +      text: "{{ if .Config.stripcyrillic }}{{ else }}{{ .Result.title_ru }} / {{ end }}{{ .Result.title_en_parsed }} {{ .Result._season_number}}E{{ .Result._episodes }} [{{ .Result._quality_type }}.{
ok

2024-03-22 17:22 UTC, merged

2024-03-22 17:22 UTC, ilike2burnthing commented
Thanks!

2024-03-23 05:58 UTC, garfield69 commented
v0.21.2140