Improve season support for UnionFansub
Jackett/Jackett pull request #15539
Opened 2024-08-16 06:00 UTC by MiguelAngelLV

#### Description

Improve season support for Union Fansub inspired by Nya indexer and add release group (fansub) to title name.

2024-08-16 06:31 UTC, garfield69 requested changes
something is not quite right.
seeing some rows returning
```
CardigannIndexer (unionfansub): Error while parsing row '
<tr>
	<td align="center" style="padding: 0px">
		<a href="browse.php?cat=1">
			<img border="0" src="./pic/caticons/cat_anime.png" alt="Anime" title="Anime">
		</a>
	</td>
	<td align="left">
		<div>
			<a href="details.php?id=(removed)&amp;hit=1">
				<b class="name">Mushoku Tensei: Isekai Ittara Honki Dasu</b>
			</a>
			<span class="fansub">Hakoniwa</span>
		</div>
	</td>
	<td align="center">
		<span class="icon jap" title="Japones"></span>
	</td>
	<td align="center">
		<span class="icon lat" title="Latino"></span>
	</td>
	<td align="center">
		<span style="white-space: nowrap;"></span>
	</td>
	<td align="right">
		<b>
			<a href="filelist.php?id=(removed)">11</a>
		</b>
	</td>
	<td align="right">0</td>
	<td align="center">
		<span style="white-space: nowrap;">175w5d</span>
	</td>
	<td align="center">7,62 GB</td>
	<td align="center">
		<a href="snatches.php?id=(removed)">255</a>
	</td>
	<td align="right">
		<b>
			<a href="peerlist.php?id=(removed)">
				<font color="#000000">10</font>
			</a>
		</b>
	</td>
	<td align="right">0</td>
	<td align="center">
		<a href="userdetails.php?id=(removed)">
			<s>Kaizer</s>
		</a>
	</td>
</tr>':

System.Exception: Error while parsing field=title_fansub, selector=td:nth-child(2) .fansubbd, value=<null>: Selector "td:nth-child(2) .fansubbd" didn't match 
```

2024-08-16 06:34 UTC, garfield69 requested changes

2024-08-16 06:34 UTC, garfield69 commented on src/Jackett.Common/Definitions/unionfansub.yml
> +      selector: td:nth-child(2) .fansubbd
```suggestion
      selector: td:nth-child(2) .fansubbd
      optional: true
```

2024-08-16 06:34 UTC, garfield69 commented on src/Jackett.Common/Definitions/unionfansub.yml
> +      text: "{{ .Result.title_season }} [{{ .Result.title_fansub }}]"
```suggestion
      text: "{{ .Result.title_season }} {{ if .Result.title_fansub }} [{{ .Result.title_fansub }}]{{ else }}{{ end }}"
```

2024-08-16 06:47 UTC, garfield69 requested changes
what is the intended outcome for `Loonatics Unleashed (Los Lunáticos) - Temporada 1ª` ?
currently getting `Loonatics Unleashed (Los Lunáticos) - Temporada`

2024-08-16 06:48 UTC, MiguelAngelLV commented
Um... It should return Los Lunaticos S1... I will check it

2024-08-16 06:54 UTC, MiguelAngelLV commented
Fixed

![image](https://github.com/user-attachments/assets/d994a0a4-a699-4812-958d-737871f58ed1)

2024-08-16 07:12 UTC, garfield69 approved these changes
LGTM

2024-08-16 07:13 UTC, merged

2024-08-17 05:56 UTC, garfield69 commented
v0.22.468