Update thegeeks.yml categories
Jackett/Jackett pull request #15603
Opened 2024-09-19 08:32 UTC by SirLouen

#### Description
- Added missing categories
- Removed categories that don't exist anymore
- Renamed some categories to match 
- Ordered all the categories to make it easy to spot and review future changes

#### Screenshot (if UI related)

#### Issues Fixed or Closed by this PR

* Missing torrent categories won't show up in the feed

2024-09-19 08:48 UTC, garfield69 commented
FYI, in future, the order that makes it easier for us to check is the order that the sites torrents page has in the HTML. 
I usually dump the HTML and compare the list with the indexer side by side.

2024-09-19 08:55 UTC, garfield69 requested changes

2024-09-19 08:55 UTC, garfield69 commented on src/Jackett.Common/Definitions/thegeeks.yml
> +    - {id: 29, cat: Other, desc: "Science: Philosophy"}
remove trailing space to comply with lint
```suggestion
    - {id: 29, cat: Other, desc: "Science: Philosophy"}
```

2024-09-19 08:55 UTC, garfield69 commented on src/Jackett.Common/Definitions/thegeeks.yml
> +    - {id: 73, cat: Other, desc: "Docu : Survivalism"}
same here
```suggestion
    - {id: 73, cat: Other, desc: "Docu : Survivalism"}
```

2024-09-19 08:58 UTC, garfield69 commented on src/Jackett.Common/Definitions/thegeeks.yml
> +    - {id: 202, cat: Other, desc: "Occultism: Mythology Folklore"}
remove duplicate category 202
```suggestion
```

2024-09-19 09:44 UTC, SirLouen commented
> FYI, in future, the order that makes it easier for us to check is the order that the sites torrents page has in the HTML. I usually dump the HTML and compare the list with the indexer side by side.

Yes, I also thought that, the problem is that the HTML follows a non responsive table format, with a fixed width of 5 columns, so basically only when 5 new categories are added you will see the same spots again, meanwhile everything is mixed up making it difficult to track the same order over time.

2024-09-19 17:17 UTC, merged

2024-09-19 17:17 UTC, garfield69 commented
Thank you.

2024-09-20 06:01 UTC, garfield69 commented
v0.22.655