Add 1ptbar index and modify soulvoice login to cookie
Jackett/Jackett pull request #9596
Opened 2020-09-22 09:31 UTC by reprover

I'm coming again!

2020-09-22 10:20 UTC, garfield69 requested changes
In future, when adding a new site, please raise a separate PR
in the event we have to back out your soulvoice change, we end up having to also back out 1ptbar.
having separate PR allows better management of changes.

2020-09-22 10:20 UTC, garfield69 commented on src/Jackett.Common/Definitions/1ptbar.yml
> +description: "SoulVoice is a CHINESE Private Torrent Tracker for Movies, TV, and e-Learning"
you forgot to update the description which is still set to soulvoice

2020-09-22 10:20 UTC, garfield69 commented on src/Jackett.Common/Definitions/1ptbar.yml
> +name: 1ptbar
don't forget to add this name to the readme.md in the private list section

2020-09-22 16:26 UTC, reprover commented
I'm sorry for my error. I'll create a new branch tomorrow since there's very late in my location. 
btw,  I'm sure it works well beacuse I'm using it :-)

2020-09-22 18:50 UTC, garfield69 approved these changes

2020-09-22 18:51 UTC, merged

2020-09-23 07:01 UTC, garfield69 commented
Jackett 0.16.1327